[project]
name = "duckdb-server"
description = "A DuckDB server for Mosaic"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "diskcache",
  "duckdb==1.1.1",
  "pandas",
  "pyarrow",
  "socketify",
  "ujson"
]

[project.scripts]
duckdb-server = "pkg.__main__:serve"

[project.urls]
homepage = "https://github.com/uwdata/mosaic"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "watchdog",
    "mypy>=1.11.1",
    "pytest>=7.4.4",
    "ruff>=0.6.1",
    "types-ujson",
]

[tool.hatch.build.targets.wheel]
packages = ["pkg"]

[tool.hatch.version]
path = "package.json"
pattern = "\"version\": \"(?P<version>.+?)\""

# https://github.com/charliermarsh/ruff
[tool.ruff]
src = ["pkg"]

[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
ignore = ["G004", "TRY301", "EM102", "EM101", "TRY003", "FBT002", "S608", "TRY002", "ARG001"]

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
files = "pkg/**/*.py"
strict = false
ignore_missing_imports = true
