[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mosaic-widget"
description = "A Jupyter widget for mosaic"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "anywidget>=0.6.3",
  "duckdb==0.9.2",
  "pyarrow"
]

[project.urls]
homepage = "https://github.com/uwdata/mosaic"

[tool.hatch.build]
artifacts = [
  "mosaic_widget/static/"
]

[project.optional-dependencies]
dev = [
  "jupyterlab",
  "pandas",
  "pyyaml",
  "ruff",
]

[tool.hatch.envs.default]
python = "3.11"
features = ["dev"]

[tool.hatch.envs.default.scripts]
style = [
  "ruff {args:../..}",
]
fmt = [
  "ruff format {args:../..}",
  "ruff --fix {args:../..}"
]

[tool.hatch.version]
path = "package.json"
pattern = "\"version\": \"(?P<version>.+?)\""

[tool.ruff]
extend-include = ["*.ipynb"]
# allow long lines, allow end in ;, allow useless expressions
ignore = ["E501", "E703", "B018"]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
